### ISSUE TITLE
https://github.com/telecom2k3/CHAOS/blob/main/CHAOS.cf#L1

### ISSUE THREAD

**Issue by xpunkt** [telecom2k3/CHAOS#5]
move this line to chaos.pre

loadplugin must not be in a cf file

thanks for the plugin btw

**Comment by telecom2k3** [comment]
Got it.  Thanks!

Post Releasum Depression (PRD):  adjective, 
                                         A Bug report in Line 1, Day 1, Hour 1

-- Jared
